/*var scheduler = new jssim.Scheduler();
var city = new jssim.Space2D();
var num_tps = 3;
var num_zcs = 4;
var num_cars_per_zone = 4;
var num_cars = num_zcs * num_cars_per_zone;
var num_riders = 0;
var carSpeed = 0.2;
var rider_probability = 80;
city.width = 1180;
city.height = 980;*/

var scheduler = new jssim.Scheduler();
var city = new jssim.Space2D();
var num_tps = 21;
var num_zcs = 16;
var num_cars_per_zone = 4;
var num_cars = num_zcs * num_cars_per_zone;
var num_riders = 0;
var carSpeed = 0.2;
var rider_probability = 80;
city.width = 1180;
city.height = 980;